DROP TABLE IF EXISTS waterings;

PRAGMA journal_mode=WAL;

CREATE TABLE waterings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day INTEGER NOT NULL,
  hour INTEGER NOT NULL,
  minute INTEGER NOT NULL,
  duration INTEGER NOT NULL
);
